### ISSUE TITLE
I cant send messages?

### ISSUE THREAD

**Issue by jebby** [xboxapi/Python-Wrapper#11]
I tried making a basic messenger with this script:
```
import requests

from xboxapi import XboxApi

api = XboxApi(api_key="MyApiKeyHere")

xuids = raw_input("Enter the Gamertag you would like to look up: ")
message = raw_input("Enter the message text you would like to send: ")


WhoIsThis = api.get_xuid_by_gamertag(xuids)


SendMessage = api.send_message(message, xuids)

print SendMessage
Pause = raw_input("Press enter to close prompt")
```

But whenever I run the script I get this error:
```
{u'errorCode': 1001, u'errorSource': u'UserInboxFrontEnd'}
```

Could you possibly tell me how to fix this or what I'm possibly doing wrong?

**Comment by ghost** [comment]
Can you try sending a message to yourself?

```python
api = XboxApi(<api_key>)
my_profile = api.get_profile()
my_xuid = my_profile["ownerXuid"]
api.send_message("Hello World", [my_xuid])
```

**Comment by jebby** [comment]
Looking over the code you gave me, it seems I made one careless mistake. 
I just started using Python yesterday and messed up on the syntax

All I did was change this:
```
import requests

from xboxapi import XboxApi

api = XboxApi(api_key="MyApiKeyHere")

xuids = raw_input("Enter the Gamertag you would like to look up: ")
message = raw_input("Enter the message text you would like to send: ")


WhoIsThis = api.get_xuid_by_gamertag(xuids)


>>> SendMessage = api.send_message(message, xuids)

print SendMessage
Pause = raw_input("Press enter to close prompt")
```

To This:

```
import requests

from xboxapi import XboxApi

api = XboxApi(api_key<MyApiKeyHere>)

xuids = raw_input("Enter the Gamertag you would like to look up: ")
message = raw_input("Enter the message text you would like to send: ")

print xuids
print message

WhoIsThis = api.get_xuid_by_gamertag(xuids)

print WhoIsThis

>>> SendMessage = api.send_message(message, [WhoIsThis])

print SendMessage
Pause = raw_input("Press enter to close prompt")
```


It seems that in the SendMessage Variable, I left the second parameter as "xuids".
I changed that to "WhoIsThis" and put it in braces and everything works. Turns out it wasn't an issue, but rather a misunderstanding to the syntax. Thank you kind sir!!!

**Comment by ghost** [comment]
I've added support for type checking on this method. Thanks :)

**Comment by ghost** [comment]
I'm not really getting how to send a message.
send_message(message, xuid)... what is a xuid, lol? is that just the gamer tag? cause i have an entire optionparse script that handles this in a dictionary, but the function wants a list. Plus the above examples do not even work for me, can you post a up to date method on sending a message? cause i really dont see an error on my end.

**Comment by ghost** [comment]
@CodeNameGhost can you please create a new issue with any code you have that is producing the error please?

**Comment by ghost** [comment]
Will do, sorry i  never really post here so idk how it works, thought this was a public chat or something lols.... ill make one soon, thanks.
