### ISSUE TITLE
Typos in request list in the documentation.

### ISSUE THREAD

**Issue by jebby** [xboxapi/Python-Wrapper#13]
In the documentation there are 3 misspelled requests:

get_xuid_by_gametag()
get_gametag_by_xuid()
get_user_gamecard()

Those didn't work for me so I looked into the source and it defines them as:
get_xuid_by_gamertag()
get_gamertag_by_xuid()
get_user_gamercard()

All 3 are missing the "r" in gamer

**Comment by ghost** [comment]
Would you mind sending a PR for this? Thanks :)

**Comment by ghost** [comment]
Fixed in 91d54ac8b2e7a41e587f189af232d02d5e77d223, closing.
