### ISSUE TITLE
Endpoint for Clubs?

### ISSUE THREAD

**Issue by oksim14** [xboxapi/Python-Wrapper#16]
Hi,

can you implement endpoint for clubs? 

https://account.xbox.com/en-us/clubs?xr=socialtwistnav

I need send post to club feed.

Is that possible?

Thank you

**Comment by djekl** [comment]
@oksim14 please make any API feature requests on the main issue repo. This is only for the Python wrapper code. @voidpirate has created this issue on there for you, and I will discuss this there.
