### ISSUE TITLE
Achievements by game

### ISSUE THREAD

**Issue by GenisDiaz** [xboxapi/Python-Wrapper#26]
Hi! at this moment I'm playing with your API. Is there some way to get achievements by game instead by a user? Or some tip to do that? 

I can get achievements if my profile has this game or if I know somebody who has played it.

Thanks for your time!

**Comment by djekl** [comment]
@GenisDiaz just get the achievements for a game using your XUID, then ignore the user information such as unlock date etc. its all the same information
