### ISSUE TITLE
Claiming tags?!

### ISSUE THREAD

**Issue by pyronlaboratory** [xboxapi/Python-Wrapper#31]
How to claim tags using this api?
Let me know if you need more details.

**Comment by pyronlaboratory** [comment]
Let me break it down further, how do you know if a gamer tag is available?

```
class Gamer(object):
    ''' Xbox profile wrapper '''

    def __init__(self, gamertag=None, client=None, xuid=None): 
   . . .
   . . .
   . . .

```
Using this, how can I figure out if a gamertag is currently available?

**Comment by djekl** [comment]
You cannot use XboxAPI to claim a gamertag, only to (in your case) check if a gamertag is available

**Comment by pyronlaboratory** [comment]
How can I check if the tag is available?

**Comment by pyronlaboratory** [comment]
Hi Alan,

Thanks for your reply.

Could you possibly share a small snippet demonstrating how to check if a
gamertag is available?
I would really appreciate your help.

Thanks,
Ronnie
