### ISSUE TITLE
Xbox clubs 

### ISSUE THREAD

**Issue by EricCacciavillani** [xboxapi/Python-Wrapper#36]
I was wondering if this API can be used for Xbox clubs. There are people who struggle heavily in a given activity in a game I play and I would like to create some way of looking over the xbox club app and help them with the given activity. Is this at all possible with your package?

**Comment by djekl** [comment]
Yes XAPI can be used with the clubs endpoint, however I didn't write this wrapper, another developer wrote this for the website.

You can see the available endpoints here - https://xapi.us/documentation

Look at endpoints 41 - 46 for club based endpoints.
