### ISSUE TITLE
Library documentation needed

### ISSUE THREAD

**Issue by ghost** [xboxapi/Python-Wrapper#4]
Documentation is needed for how to use this package

**Comment by aptrishu** [comment]
I want to be assigned but I, myself don't know how to use this package. are you going to guide me?

**Comment by susanesho** [comment]
am guessing this is a script that consumes xbox api.  can I request to claim this issue?

**Comment by ghost** [comment]
Yes, that is correct.

The documentation should include how to install the module and basic example (including the response from the api). Might also be helpful to include an examples directory with a script that can be ran.

**Comment by ghost** [comment]
@aptrishu  @andela-oesho

**Comment by susanesho** [comment]
@voidpirate thanks for the insight. I would be claiming the issue
